name: tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      - run: go version
      - run: go test ./...
      - run: go build ./cmd/mcutils